apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-ebs-csi-driver-operator
  namespace: openshift-cluster-csi-drivers
  annotations:
    storage.openshift.io/remove-from: guest
spec:
  replicas: 1
  selector:
    matchLabels:
      name: aws-ebs-csi-driver-operator
  strategy: {}
  template:
    metadata:
      annotations:
        target.workload.openshift.io/management: '{"effect": "PreferredDuringScheduling"}'
        openshift.io/required-scc: restricted-v2
      labels:
        name: aws-ebs-csi-driver-operator
        openshift.storage.network-policy.api-server: allow
    spec:
      containers:
      - args:
        - start
        - -v=${LOG_LEVEL}
        env:
        - name: DRIVER_IMAGE
          value: ${DRIVER_IMAGE}
        - name: PROVISIONER_IMAGE
          value: ${PROVISIONER_IMAGE}
        - name: ATTACHER_IMAGE
          value: ${ATTACHER_IMAGE}
        - name: RESIZER_IMAGE
          value: ${RESIZER_IMAGE}
        - name: SNAPSHOTTER_IMAGE
          value: ${SNAPSHOTTER_IMAGE}
        - name: NODE_DRIVER_REGISTRAR_IMAGE
          value: ${NODE_DRIVER_REGISTRAR_IMAGE}
        - name: LIVENESS_PROBE_IMAGE
          value: ${LIVENESS_PROBE_IMAGE}
        - name: KUBE_RBAC_PROXY_IMAGE
          value: ${KUBE_RBAC_PROXY_IMAGE}
        - name: TOOLS_IMAGE
          value: ${TOOLS_IMAGE}
        - name: OPERATOR_IMAGE_VERSION
          value: ${OPERATOR_IMAGE_VERSION}
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        image: ${OPERATOR_IMAGE}
        imagePullPolicy: IfNotPresent
        name: aws-ebs-csi-driver-operator
        resources:
          requests:
            memory: 50Mi
            cpu: 10m
        terminationMessagePolicy: FallbackToLogsOnError
      serviceAccountName: aws-ebs-csi-driver-operator
