apiVersion: cloudcredential.openshift.io/v1
kind: CredentialsRequest
metadata:
  name: azure-file-csi-driver-operator
  namespace: openshift-cloud-credential-operator
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    capability.openshift.io/name: Storage+CloudCredential
spec:
  serviceAccountNames:
  - azure-file-csi-driver-operator
  - azure-file-csi-driver-controller-sa
  - azure-file-csi-driver-node-sa
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: AzureProviderSpec
    permissions:
      - 'Microsoft.Storage/storageAccounts/read'
      - 'Microsoft.Storage/storageAccounts/write'
      - 'Microsoft.Storage/storageAccounts/listKeys/action'
      - 'Microsoft.Storage/operations/read'
      # this is only necessary if the driver creates the storage account with a private endpoint:
      - 'Microsoft.Network/virtualNetworks/join/action'
      - 'Microsoft.Network/virtualNetworks/subnets/join/action'
      - 'Microsoft.Network/virtualNetworks/subnets/write'
      - 'Microsoft.Network/virtualNetworks/subnets/read'
      - 'Microsoft.Network/privateEndpoints/write'
      - 'Microsoft.Network/privateEndpoints/read'
      - 'Microsoft.Network/privateEndpoints/privateDnsZoneGroups/read'
      - 'Microsoft.Network/privateEndpoints/privateDnsZoneGroups/write'
      - 'Microsoft.Network/privateDnsZones/join/action'
      - 'Microsoft.Network/privateDnsZones/write'
      - 'Microsoft.Network/privateDnsZones/virtualNetworkLinks/write'
      - 'Microsoft.Network/privateDnsZones/virtualNetworkLinks/read'
      - 'Microsoft.Network/privateDnsZones/read'
      - 'Microsoft.Network/privateDnsOperationStatuses/read'
      - 'Microsoft.Network/locations/operations/read'
      - 'Microsoft.Storage/storageAccounts/PrivateEndpointConnectionsApproval/action'
      # this is only necessary if the subnet carrying the write permission has these additional resources configured:
      - 'Microsoft.Network/serviceEndpointPolicies/join/action'
      - 'Microsoft.Network/natGateways/join/action'
      - 'Microsoft.Network/networkIntentPolicies/join/action'
      - 'Microsoft.Network/networkSecurityGroups/join/action'
      - 'Microsoft.Network/routeTables/join/action'
      - 'Microsoft.Network/networkManagers/ipamPools/associateResourcesToPool/action'
      # OCP carry: those are not listed upstream
      - 'Microsoft.Storage/storageAccounts/fileServices/read'
      - 'Microsoft.Storage/storageAccounts/fileServices/shares/delete'
      - 'Microsoft.Storage/storageAccounts/fileServices/shares/read'
      - 'Microsoft.Storage/storageAccounts/fileServices/shares/write'

  secretRef:
    name: azure-file-credentials
    namespace: openshift-cluster-csi-drivers

