apiVersion: cloudcredential.openshift.io/v1
kind: CredentialsRequest
metadata:
  name: azure-disk-csi-driver-operator
  namespace: openshift-cloud-credential-operator
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    capability.openshift.io/name: Storage+CloudCredential
spec:
  serviceAccountNames:
  - azure-disk-csi-driver-operator
  - azure-disk-csi-driver-controller-sa
  - azure-disk-csi-driver-node-sa
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: AzureProviderSpec
    permissions:
      - Microsoft.Compute/disks/read
      - Microsoft.Compute/disks/write
      - Microsoft.Compute/disks/delete
      - Microsoft.Compute/diskEncryptionSets/read
      - Microsoft.Compute/snapshots/read
      - Microsoft.Compute/snapshots/write
      - Microsoft.Compute/snapshots/delete
      - Microsoft.Compute/virtualMachines/write
      - Microsoft.Compute/virtualMachines/read
      - Microsoft.Compute/virtualMachineScaleSets/virtualMachines/write
      - Microsoft.Compute/virtualMachineScaleSets/virtualMachines/read
      - Microsoft.Compute/virtualMachineScaleSets/read
      - Microsoft.Compute/locations/operations/read
      - Microsoft.Compute/locations/DiskOperations/read
      - Microsoft.Resources/subscriptions/resourceGroups/read
      - Microsoft.Resources/subscriptions/resourceGroups/*/read
      # Those are needed only when the virtualMachine or virtualMachineScaleSets have these additional resources configured:
      - Microsoft.Compute/disks/beginGetAccess/action
      - Microsoft.KeyVault/vaults/deploy/action
      - Microsoft.ManagedIdentity/userAssignedIdentities/assign/action
      - Microsoft.Network/applicationGateways/backendAddressPools/join/action
      - Microsoft.Network/applicationSecurityGroups/joinIpConfiguration/action
      - Microsoft.Network/loadBalancers/backendAddressPools/join/action
      - Microsoft.Network/loadBalancers/inboundNatPools/join/action
      - Microsoft.Network/loadBalancers/probes/join/action
      - Microsoft.Network/networkInterfaces/join/action
      - Microsoft.Network/networkSecurityGroups/join/action
      - Microsoft.Network/publicIPPrefixes/join/action
      - Microsoft.Network/virtualNetworks/subnets/join/action
  secretRef:
    name: azure-disk-credentials
    namespace: openshift-cluster-csi-drivers
