apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-disk-csi-driver-operator
  namespace: openshift-cluster-csi-drivers
  annotations:
    storage.openshift.io/remove-from: guest
    config.openshift.io/inject-proxy: azure-disk-csi-driver-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: azure-disk-csi-driver-operator
  strategy: {}
  template:
    metadata:
      annotations:
        openshift.io/required-scc: restricted-v2
        target.workload.openshift.io/management: '{"effect": "PreferredDuringScheduling"}'
      labels:
        name: azure-disk-csi-driver-operator
        openshift.storage.network-policy.dns: allow
        openshift.storage.network-policy.api-server: allow
        openshift.storage.network-policy.operator-metrics-range: allow
    spec:
      containers:
      - args:
        - start
        - -v=${LOG_LEVEL}
        env:
        - name: DRIVER_IMAGE
          value: ${DRIVER_IMAGE}
        - name: PROVISIONER_IMAGE
          value: ${PROVISIONER_IMAGE}
        - name: ATTACHER_IMAGE
          value: ${ATTACHER_IMAGE}
        - name: RESIZER_IMAGE
          value: ${RESIZER_IMAGE}
        - name: SNAPSHOTTER_IMAGE
          value: ${SNAPSHOTTER_IMAGE}
        - name: NODE_DRIVER_REGISTRAR_IMAGE
          value: ${NODE_DRIVER_REGISTRAR_IMAGE}
        - name: LIVENESS_PROBE_IMAGE
          value: ${LIVENESS_PROBE_IMAGE}
        - name: KUBE_RBAC_PROXY_IMAGE
          value: ${KUBE_RBAC_PROXY_IMAGE}
        - name: CLUSTER_CLOUD_CONTROLLER_MANAGER_OPERATOR_IMAGE
          value: ${CLUSTER_CLOUD_CONTROLLER_MANAGER_OPERATOR_IMAGE}
        - name: OPERATOR_IMAGE_VERSION
          value: ${OPERATOR_IMAGE_VERSION}
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        image: ${OPERATOR_IMAGE}
        imagePullPolicy: IfNotPresent
        name: azure-disk-csi-driver-operator
        resources:
          requests:
            memory: 50Mi
            cpu: 10m
        terminationMessagePolicy: FallbackToLogsOnError
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - mountPath: /tmp
          name: tmp
      serviceAccountName: azure-disk-csi-driver-operator
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      volumes:
      - name: tmp
        emptyDir:
          medium: Memory
