kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: volume-data-source-validator
rules:
  - apiGroups: [populator.storage.k8s.io]
    resources: [volumepopulators]
    verbs: [get, list, watch]
  - apiGroups: [""]
    resources: [persistentvolumeclaims]
    verbs: [get, list, watch]
  - apiGroups: [""]
    resources: [events]
    verbs: [list, watch, create, update, patch]
  - apiGroups: [coordination.k8s.io]
    resources: [leases]
    verbs: [get, list, watch, create, update, patch, delete]
  - apiGroups: [authentication.k8s.io]
    resources: [tokenreviews]
    verbs: [create]
