kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: volume-data-source-validator
subjects:
  - kind: ServiceAccount
    name: volume-data-source-validator
    namespace: openshift-cluster-storage-operator
roleRef:
  kind: ClusterRole
  name: volume-data-source-validator
  apiGroup: rbac.authorization.k8s.io
